name: github_actions_toolkit
description: Toolkit containing useful methods to build a GitHub Action with Dart.
version: 0.0.7
repository: https://github.com/axel-op/github_actions_toolkit.dart
homepage: https://github.com/axel-op/github_actions_toolkit.dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  synchronized: ^3.0.0

dev_dependencies: 
  lints: ^2.1.0
