name: Package analysis

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
