name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: dart:stable

    steps:
      - uses: actions/checkout@v2
      - name: Run test app
        id: dart-app
        uses: ./tool
      - name: Test
        run: |
          if [ -z "${{ steps.dart-app.outputs.time }}" ]; then
            echo "No output"
            exit 1
          fi
          echo "$PATH" | grep -q "/doesntexist"
          CODE=$?
          if [ "$CODE" -ne 0 ]; then
            echo "Path not set"
            exit 1
          fi
          if [ "$TEST_ENV" != "Testvalue" ]; then
            echo "Environment variable not set"
            exit 1
          fi

  publishable:
    runs-on: ubuntu-latest
    container: dart:stable

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Run dartdoc
        run: dartdoc
      - name: Test pub publish
        run: dart pub publish --dry-run
